// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Presentation.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Persistence.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Start your day with a relaxing yoga session. Perfect for all skill levels.",
                            EndTime = new DateTime(2025, 9, 17, 8, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Studio A",
                            StartTime = new DateTime(2025, 9, 17, 7, 0, 0, 0, DateTimeKind.Local),
                            Title = "Morning Yoga"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "High-intensity interval training to boost your metabolism and strength.",
                            EndTime = new DateTime(2025, 9, 17, 19, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Main Floor",
                            StartTime = new DateTime(2025, 9, 17, 18, 0, 0, 0, DateTimeKind.Local),
                            Title = "HIIT Training"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Energetic cycling workout with motivating music and expert instruction.",
                            EndTime = new DateTime(2025, 9, 18, 10, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Spin Studio",
                            StartTime = new DateTime(2025, 9, 18, 9, 0, 0, 0, DateTimeKind.Local),
                            Title = "Spin Class"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Build muscle and improve your overall strength with guided weight training.",
                            EndTime = new DateTime(2025, 9, 18, 18, 30, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Weight Room",
                            StartTime = new DateTime(2025, 9, 18, 17, 0, 0, 0, DateTimeKind.Local),
                            Title = "Strength Training"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Improve flexibility, balance, and core strength with this low-impact workout.",
                            EndTime = new DateTime(2025, 9, 19, 11, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Studio B",
                            StartTime = new DateTime(2025, 9, 19, 10, 0, 0, 0, DateTimeKind.Local),
                            Title = "Pilates"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Workout of the Day featuring functional movements at high intensity.",
                            EndTime = new DateTime(2025, 9, 19, 20, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "CrossFit Box",
                            StartTime = new DateTime(2025, 9, 19, 19, 0, 0, 0, DateTimeKind.Local),
                            Title = "CrossFit WOD"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Low-impact water-based exercise that's easy on joints but tough on calories.",
                            EndTime = new DateTime(2025, 9, 20, 12, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Pool Area",
                            StartTime = new DateTime(2025, 9, 20, 11, 0, 0, 0, DateTimeKind.Local),
                            Title = "Aqua Fitness"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Fun and energetic dance fitness class with Latin and international music.",
                            EndTime = new DateTime(2025, 9, 21, 19, 30, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Dance Studio",
                            StartTime = new DateTime(2025, 9, 21, 18, 30, 0, 0, DateTimeKind.Local),
                            Title = "Zumba Dance"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "One-on-one training session customized to your fitness goals.",
                            EndTime = new DateTime(2025, 9, 22, 15, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "PT Room 1",
                            StartTime = new DateTime(2025, 9, 22, 14, 0, 0, 0, DateTimeKind.Local),
                            Title = "Personal Training Session"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Relax and center yourself with guided meditation and breathing exercises.",
                            EndTime = new DateTime(2025, 9, 23, 9, 0, 0, 0, DateTimeKind.Local),
                            Location = "Core Gym Haninge",
                            LocationRoom = "Quiet Room",
                            StartTime = new DateTime(2025, 9, 23, 8, 0, 0, 0, DateTimeKind.Local),
                            Title = "Meditation & Mindfulness"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
